Vagrant.configure("2") do |config|
    config.vm.box = "csub_base"
    config.vm.provider :virtualbox do |v|
      v.memory = 4096
    end
  
    config.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
    
    config.vm.provision :shell, inline: "sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -"
    config.vm.provision :shell, inline: "sudo apt-get update -y"
    config.vm.provision :shell, inline: "sudo apt-get upgrade -y"
    config.vm.provision :shell, inline: "sudo apt-get install -y nodejs"
    config.vm.provision :shell, inline: "sudo apt install build-essential -y"
    config.vm.provision :shell, inline: "sudo npm install pm2 -g"
    config.vm.provision :shell, inline: "pm2 start /vagrant/file-server/src/index.js"
    config.vm.provision :shell, inline: "pm2 save"
    config.vm.provision :shell, inline: "pm2 startup"
  end