Vagrant.configure("2") do |config|
    config.vm.box = "csub_base"
    config.vm.provider :virtualbox do |v|
      v.memory = 4096
    end
  
    config.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
    
  end